sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install -g
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: gt/xunNUIoRFEkKejjTFwA8CkyTcOKi+7fEZKwEHfVEXXnNDCicacbfzwgmtHPKRkmGt7wXzsYVJiTZF+Ahbgs/aLmslPPjqfrTf5/ZAC89xJNuhBcrQ+cKKPk1zmZzwkOHVW8mafJPodVJcnGkYkpFEcAldMq3QfthlO4yPQIMRYqT1rjUSgrHcd9BWynpfZBbdOOZmv6ytr1ZWacf+PC4c1rYGhELfdc60Gszg8aDfuwQo18tvCPO2QGfsTfRf99Q5oqTGnk7AVj+cwnQ/si7uoXbgVUajsSukmwREJH+UQaTKPlBwvexXxXRqg1LSQI5DpzRQaWrtcj4qqTzJlyZAD9uYPPvQu9VZe0BFdOXrwA3ETbTyESgHSQ10vYPkHFW86XpBkrhF9wOwQHjPDexzQAcS+U4ZpL2eNQ3WorjzZkl2+Fz5QLmSc8PzAbRNpFukW2/C2ZKK81f8VW+Q3L7za/Wl5u2d3o2CuX23eeXMUQyV9nPCC9TxvcaclUPWt6wXqL50IpU4B8pinTbKP0+zfUF3wX0eUV3xzPeZh0yPaLPXvqzcMBqArNV8rZIAaWF1KqDOhQ2Q7ShYQk3nNzh5YNqIAu+oCtH0t7Ppk2AC/PHkoJFEJLdIVMY8WmHsP+imcIdTBM6Y+CdQAfUS4t6eoC8k/cvLqgfykAiZc7E=
  - secure: gZevyW8Rs86NeudLKKjP8vyyAKJI95XeZdhBpcxhTJ6q2sP2rfhngvlTceWcbwpRH8Zqg1KQc5Jb+WdbEbvDP9CH06hPd3qH7gDPRON4zredzJaHHMx3n+KFlcZEd7iRktF5zlOaTIWEC/7DSvz9Z8qRS1SLrOph3Ms53R6hVrhHG/FqAN8yxuNS+KByKhrtflm7ARZVdIhsM7znjNLRl8dGV8kpTM5LLxAMKoFdw2ktLbrHD37LdBgjWXx6exSFBFdZE0Aw4iM0DK++pdKll9ik9ZpDUyBGEnlkVI7k9G9kkn85/XTtNWO93bfI3V69fjoZidT442UFt8jV8LAo3Qo7Gk/6AaE0oVBopFrCqS2HU+BBGFTpafoSkqUW4IS0WtqL3NhC2MPz4LIpT/rcT47UCc+LO6aWMIjBmWxrqriVmHl4XIWx26iq1Yrm77QVWNHhYFZJCDyOEZsyESf5qjyJMGY/bXjYa5Y5hZ5WU6qYl56BFooFOGxvjI6iwL9e+4oXhhhPd50snc+lif3um9BjzeD52bX2k6M9MsXDU943S/QziFk16CRF60/82t9+VBX6ObzxOMWLXQyOTSg9sUFO10FGiWkwnVPXZXxofUVZyUs01dB3nZk7uNMpHeIQb4V512NqH9Un6HekBayWXJ2FuGef9Tu913ZCWNJDMlM=
